version: '3.8'

services:
  db:
    image: mariadb:10.3.23
    container_name: db01
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
    ports:
      - "3306:3306"
    volumes:
      - ./.db_data:/var/lib/mysql
    restart: always
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
